version: '3.8'

services:
  
  frontend-service:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://3.110.48.166:5000
  # backend-service:
  # build: ./backend
  # ports:
  #  - "5000:5000"
